spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: cuenta-movimientos-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer